---
title: "Main Scratch"
author: "K Todd-Brown (ktoddbrown@ufl.edu)"
date: "7/20/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(yaml)
```



# Translation data model

```{r}
data_dir <- 'data_download'

dataSources <- read_csv(file.path('meta', 'bulk_density_metadata - data_source_v2.csv')) %>%
  filter(!is.na(data_download_URL)) %>%
  filter(data_source_ID %in% c('Howard2020', 'Kusumaningtyas2018a')) %>%
  separate_rows(data_download_URL, data_filename, sep = ';') %>% ##TODO Ensure the same number of ; in both columns
  mutate(data_filename = trimws(data_filename),
         data_download_URL = trimws(data_download_URL)) %>%
  mutate(download_file = file.path(data_dir, data_source_ID, data_filename))


plyr::d_ply(dataSources, c('data_filename'), function(xx){
  createDir_log <- dir.create(dirname(xx$download_file))
  download.file(xx$data_download_URL, destfile = xx$download_file)
  if(grepl('\\.zip$', xx$download_file)){
    unzip(zipfile = xx$download_file, exdir = dirname(xx$download_file))
  }
})


```

## Bulk density

TODO
  - write a formatting enforcer for this metadata

```{r}
bulk_density.ls <- list(bulk_density = list(description = 'Bulk density - dry soil to volume ratio, specify inclusion of coarse fraction in data', 
                                            type = 'numeric', min = 0, max = Inf),                        
                        bulk_density_units = list(description= 'Bulk density unit [mass per volume]', 
                                                  type = 'character'),
                        bulk_density_includes_coarse_fraction = list(description = 'Flags inclusion of coarse fraction in bulk density value',
                                                                     type = 'logical'),
                        Coarse_fraction = list(description = 'Coarse fraction', 
                                               type = 'numeric', min = 0, max = 1),
                        Coarse_fraction_unit = list(description = 'Coarse fraction unit', 
                                                    type = 'factor', 
                                                    factors = list(mass_ratio = 'ratio of coarse fraction mass to whole soil mass [common]', 
                                                                   volume_ratio = 'ratio of coarse fraction volume to whole soil volume [rare]')),
                        Coarse_fraction_method = list(description = 'Coarse fraction separation methods', 
                                                      type = 'factor', 
                                                      factors = list(sieve_2mm = ' >2mm sieve size [common]', 
                                                                     hand_picked = 'hand picked large partices (ex roots, and rocks), generally peats [rare]')),
                        Bulk_density_volume_method = list(description = 'Bulk density volume method', 
                                                          type = 'factor',
                                                          factors = list(geometric_volume = 'Volume by extracted slice or core geometry.',
                                                                         compliant_cavity = 'Fill hole with material of known density',
                                                                         clod = 'Volume by displacement of soil mass.',
                                                                         auger_cores = 'Internal core volume of an auger core',
                                                                         imaged_volume = '3D scan for volume of soil clod')
                        ))
```

```{r eval=FALSE}
##Save things in yaml when needed
write_yaml(bulk_density.ls, file = 'data_model/bulk_density.yml')
cat(sprintf('%s\n', readLines('data_model/bulk_density.yml')))
```

## Data source

```{r}
data_source.ls <- list(data_source_ID = list(desciption = 'Internal study identifier; convention [FirstAuthorLastName-GroupName][Year][abc] ex Yamshito2015a',
                                             type = 'character'), #TODO formatting check here?
                       data_source_title = list(desciption = 'Long title of data source',
                                                type = 'character'),
                       data_access = list(description = 'how the data was accessed',
                                          type = 'factor',
                                          factor = list(data_package = 'download as a data package zip file including metadata and data tables, could include paper as well',
                                                        data_table_files = 'download as individual data tables with one header row regular structure. Possible meta information in header defined as /* */ from pangaea',
                                                        data_rescue = 'manual or scripted extraction needed from a scanned document or non-regular table'
                                          )),
                       data_download_URL = list(description = 'list of for data download, as ; seperated list',
                                                type = 'character'), #TODO formatting check here?
                       data_filename = list(description = 'list of data file names that match the data downloads',
                                                type = 'character'),
                       data_citation = list(description = 'suggested data citation',
                                            type = 'character'),
                       data_DOI = list(description = 'DOI for associated data object',
                                       type = 'character'), #TODO formatting check
                       data_published_year = list(description = 'Year data was published [Common Era]',
                                                  type = 'numeric'),
                       abstract = list(description = 'Abstract for data citation',
                                       type = 'character'),
                       notes = list(description = 'Free notes field: why this data source was selected,list of data variables, keywords, and associated publications',
                                    type = 'character'))
```

```{r eval=FALSE}
##Save things in yaml when needed
write_yaml(data_source.ls, file = 'data_model/data_source.yml')
cat(sprintf('%s\n', readLines('data_model/data_source.yml')))
```

